#pragma once

#include "NativeGameplayTags.h"

namespace LshPF_GameplayTags
{
    // Test Tag
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_Test1);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_Test2);
	
	// Widget Stack
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_Modal);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_GameMenu);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_GameHud);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_WidgetStack_Frontend);

	//Widgets
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_ConfirmScreenBase);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_PressAnyKey);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_MainMenu);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_Status);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_Command);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_Skill);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_Item);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Widget_CharacterInfo);
	
	//Levels
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Level_MainMenu);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_Level_Battle);

	//InputAction Tag
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_DefaultConfirm);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_DefaultBack);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_Attack);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_Guard);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_OpenSkill);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_OpenItem);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_SelectTarget_Prev);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_SelectTarget_Next);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_CharacterInfo);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_InputAction_TargetTypeSwitch);
	
	//Anim Montage
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_AnimMontage_Attack);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_AnimMontage_Skill);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_AnimMontage_Death);
	LSHPF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LshPF_AnimMontage_HitReact);
}